name: java workflow
on: 
  push:
    branches:
      - none

jobs:
  java_demo:
    runs-on: ubuntu-latest

    steps:
      - name: check repository
        uses: actions/checkout@v4
          
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'   # JDK vendor
          java-version: '17'        # JDK version

      - name: Compile java file
        run: javac hello.java

      - name: Run java application
        run: java hello
